default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 1 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", 'localhost') %>
  port: <%= ENV.fetch("POSTGRES_PORT", '5434') %>
  username: <%= ENV.fetch("POSTGRES_USER", 'postgres') %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", 'app') %>

development:
  <<: *default
  database: e-commerce_development


test:
  <<: *default
  database: e-commerce_test

production:
  <<: *default
  database: e-commerce_production
